name: Update README

on:
  push:
    paths:
      - config.json
      - README_template.md
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        
    - name: Fetch config.json
      run: |
        curl -O https://raw.githubusercontent.com/u8-zawa/auto-update-readme-github-actions/main/config.json > config.json
        cat config.json
        echo "VERSION=$(jq -r .version config.json)" >> $GITHUB_ENV
    
    - name: List Ubuntu Environment Variables
      run: env
    
    - name: Run update_readme.py
      run: python update_readme.py

    - name: Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update README
        file_pattern: 'README.md'
